apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-clean-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-clean-app
  template:
    metadata:
      labels:
        app: nest-clean-app
    spec:
      containers:
      - name: nest-clean
        image: robsu1/nest-clean:v2
        ports:
        - containerPort: 3000
        env: 
          - name: DATABASE_URL
            value: "postgresql://postgres:docker@postgres-service:5432/nest_clean?schema=public"
          - name: JWT_PUBLIC_KEY
            value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbkNvdWFmRnZ6TzdRWGRzVjdFeWoNCjBiYjhReUlXaWdRQlB2U3cvUno4ak13ZXYvdEk3WS81YVh2alFrNENLdUNBMWgxL3NZYVFMZU44NytTd2ZUK0gNCndOcTk0UFdEeDlXMTdpWTJYYkg5NTJQMDBaODltaUpWV2NjMzVSckhaS2tqbEJETlF2dnNreWhRcGJqR2V0NVQNCkxTdWRneElyaXZ4UHNOOVRHdUt2RUFTMjhYenhONGhidmw4dHlTRnpiZzA4NnA2Rld2dHlEVzZzK1VRM2xSMzcNCkhPYXpUMTJUeXdZQ3ZLS2ZIVW5CaUU2aXN2azNoUnR1eklFOWhkZ0Rpa08xUzVweWNqcWVXOVBLa0d2YURQdWUNCjVtdU1mWG1VTURaSmN4NDhUTG12RkZQUnBQLzU2YjFrYXF6M0xLUUhiRk8wSExGTGUyQUQ1Ynd3NWFYa21nSHkNCmtRSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg"
          - name: JWT_PRIVATE_KEY
            value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUNjS2k1cDhXL003dEJkDQoyeFhzVEtQUnR2eERJaGFLQkFFKzlMRDlIUHlNekI2LyswanRqL2xwZStOQ1RnSXE0SURXSFgreGhwQXQ0M3p2DQo1TEI5UDRmQTJyM2c5WVBIMWJYdUpqWmRzZjNuWS9UUm56MmFJbFZaeHpmbEdzZGtxU09VRU0xQysreVRLRkNsDQp1TVo2M2xNdEs1MkRFaXVLL0UrdzMxTWE0cThRQkxieGZQRTNpRnUrWHkzSklYTnVEVHpxbm9WYSszSU5icXo1DQpSRGVWSGZzYzVyTlBYWlBMQmdLOG9wOGRTY0dJVHFLeStUZUZHMjdNZ1QyRjJBT0tRN1ZMbW5KeU9wNWIwOHFRDQphOW9NKzU3bWE0eDllWlF3TmtsekhqeE11YThVVTlHay8vbnB2V1JxclBjc3BBZHNVN1Fjc1V0N1lBUGx2RERsDQpwZVNhQWZLUkFnTUJBQUVDZ2dFQUFkN3lQNGRpbVB2SDNxWlJMVER4bkpHdXlkL2JjWSs0Mks2M2ZRVWpIQzEyDQpSVU9TOFFnb0dLTm1UVFBUQVlnZkk2N2hWS1g5aUdtS0x4T2xmdVJOMlpHbW85UGQwN0oveE45YnN1dzBNLzRIDQpRa002NytPdk03V0ttZWhwU09vZ2FmaDRlZy9iaXFZMEdhUFV5bWJyUVRrTmNLTWRNYmtDUENhL3g2Y2RYMnhCDQo2WmRwMnBrMmxSRW9IQ1gzSnBRUi8vUHVoQkRTeGFlUEhUdkt0d0FuOGxwMzljUmUzQ3VXM0gxQkZsT3E3RGlMDQpNelZnSFpCSzI5VXE5V1U1L0xtblZzNlFUTDZ3ZTdEbVJQbkx1TlJZUlp2TmZLaU1hWmlQWlVydmtNMTcwL3FKDQpMcVlKWjRIcE5vY2g4VlhhZG9CTjIxSUl1WGZHVDBsczJiMjBSRWswZ1FLQmdRREpUWWJRU1NuVndLRFpmODVSDQpoVjNjeURrSk1ndUYxTUVlREh4eVhvUDBEM21jNmI0SUIyajJWbjltYVp6OXVhSVNwOWtSNTlld2tFdisxdE5sDQpVMU8rNFl4WnB0U3FZc1JxZXg4Y1JWOHNlM1JyOXhUOTM0NjY0bTZpVm5XZXN5cVQyenJXbmJqZTA2SW1uLzJUDQoxVnFHYjNXRjlFazhzcWZpNXRyUThWUmNFUUtCZ1FER21PS0NMRUFFNTVpRVp2aVlnT3ZIV1ord1piZWFLL0x3DQp5ZFArYkFQR1NYRGU2d2phbTd4a3lCUkVHQmRVa2llSC9rYXk5d3crZnlZcitlQWFzZGRLWVJmV1B5OVltenFNDQp0SGx5dWQvcnNQRFZPNVgreG14ZUFyNk5EWGx1MzIzZE1oVmlYNzQyWkhQTEUvMEdCWmhoUVNldGJSMFdJQlcwDQo3VGRQaFN5dWdRS0JnUUNBRDQzZ0cyczl6Rm1IaEVMZ29aTmd6UTlieGphR1lSNnAydytnUW5oM1h4RGl2ZUJpDQpnelJHNGlnU0lzWDRzNHRqaXR3UkJBaTNEbFVLUGVnbDRhaTVHZ3VMVFJLbGdrZXA1Y0dZM3BqNVYyQnMvcmFmDQord1IxNTI2eVg0WmIrMmJ1d056aGcxMEVoR1gzWkhpUS8zMmpZR3pIVnV6d2JFZFpsYnRHaVFBOXdRS0JnUUNHDQo2WXRPbFJMMGdnUlpSYjV4azNzWTFPaW5vNklEcVFHRDFBZ2cyVzREQVJjZFNKdWVMcGZmK3cvUlpuQks4bkxLDQpidEhHZUErb1VTWTBUNjZQVStzR1Mwa3ZNWU5QZFR4a0k2SXhidFlRUGdhTlJNcFQ1cVh0ZzMzQlFyc1F0OVhoDQpvMGxscDljSENseWpRN1BxcUZocEVTTU1MSWpLNUFiNi92OUpGUlpTZ1FLQmdCdzVyb3F3LzdZK2tsL0lVSFduDQorMGJUaFZkK2FvTENvMXZmUlA1OEEreFNsWTlIYm1HQnppdXFIZ3JQZ3RCRTFhN0MxMTJiR2FQQWNkR3FlenVWDQpkMDJ3ZWtpM3RFb1FQVERVSEl4dVNicFNMS1hmT2s1WjA1c0VBNzIyaVF0YWFSUTludUVYUUJBREJvalFOT1prDQpNUDZ6M3hkTk1IN09xVHRLYUNBMUxkYngNCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg"
          - name: PORT
            value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: nest-clean-service
spec:
  selector:
    app: nest-clean-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
